### ISSUE TITLE
The ad duration is displayed as video/movie duration after skipping ad

### ISSUE THREAD

**Issue by odmivolsi** [webtor-io/player-sdk-js#10]
Sometimes when i skip an ad, the player shows the total length of the video to be played as the length of the ad I just skipped. 

_For eg_- if an ad is 15 seconds long and the video is 1 hour long, the player keeps showing 15 seconds as the total duration of the video. On crossing the 15 sec mark, the video keeps playing. 

It does not cause an issue functionally, but sometimes a viewer may think they have opened the wrong video because of the short duration showed.

**Comment by odmivolsi** [comment]
Update: there is an issue functionally that the user cannot go forward or back using the scrub bar / seek bar

**Comment by odmivolsi** [comment]
@vintikzzz help me out here

**Comment by vintikzzz** [comment]
Hi can you provide screenshots?
Also specify browser and OS, so I will be able to reproduce!

**Comment by odmivolsi** [comment]
@vintikzzz This is happening in chrome on Android. I haven't tested it on other platforms.
 I have attached a Screenshot of a movie I was trying to watch where the ad was 3 minutes long and the player kept showing the duration of the movie as 3 minutes. Screenshot is attached below
![Screenshot_20200726-020657__01 (1).jpg](https://user-images.githubusercontent.com/66444874/88466121-b2f61f00-ceb8-11ea-88ad-db5bc69b8293.jpg)

**Comment by vintikzzz** [comment]
Webtor transcodes movie on the fly and it shows duration of transcoded part in the player. You have just to wait a little bit. It might be confusing at first time.

**Comment by odmivolsi** [comment]
But this will make many people think that they have opened the wrong movie file

**Comment by wlasser** [comment]
This will be good feauture with implementing showing total movie time, and separate progressbar for loaded segments of HLS, but with disabled scrolling to not loaded pieces.

**Comment by vintikzzz** [comment]
Yes, It's really good thing, unfortunately there is no option in my current video player (Mediaelement.js) to set custom video length. If you can point me some solution to impement it will be really appreciated!

**Comment by odmivolsi** [comment]
@vintikzzz  have you tried powder web?

**Comment by vintikzzz** [comment]
@odmivolsi I have tried to install it today, but no luck... a lot of errors occured. What can I learn from this project?

**Comment by wlasser** [comment]
@vintikzzz VideoJS with HLS module have good api for exactly that operations. You can get all loaded segment, walk through loaded pieces, start from any position.

**Comment by vintikzzz** [comment]
@wlasser the main problem that I don't know exact number of HLS-fragments to pregenerate VOD HLS playlist. It is only possible with real transcoding (not just "copy stream"), but it makes low quality video-stream on fast ffmpeg presets. There is some trade off. You can read about it at [release notes for revision 1.6.0](https://blog.webtor.io/en/post/new-features-in-webtor-1.6.0/). By the way, I have used Video JS with HLS module at first version, but there was no ability to correctly process HLS live-streams.

**Comment by wlasser** [comment]
@vintikzzz i am currently use VideoJS with webtor, but without modification in this way (just playback) i'll check something when be free.

**Comment by odmivolsi** [comment]
@vintikzzz please try to fix this

**Comment by vintikzzz** [comment]
@odmivolsi  I can try to show full duration but there will be no option to fast forward, is it ok?

**Comment by odmivolsi** [comment]
@vintikzzz we will be able to go ahead or back using the scrubber right? Im assuming by fast forward you mean double tap to skip 10 seconds

**Comment by vintikzzz** [comment]
@odmivolsi no, there will be no option to change postition to non-transcoded part. For example if we have 2 hours movie and there was already 30 minutes transcoded from the beginning. In this case we will be able to see full timeline, but we will be able only to change poistion only in the part of the movie that was already transcoded, first 30 minutes. Transcoding goes from the very beginning to the end continuosly.

**Comment by odmivolsi** [comment]
@vintikzzz this might cause some issues but its worth a try. I think this should work for the most part

**Comment by vintikzzz** [comment]
@odmivolsi I have done as we discussed before, but it shouldn't work the same in fullscreen on Android/iOS devices. They use native players for HLS, so I can't override their behaviour.

**Comment by odmivolsi** [comment]
@vintikzzz the movie duration bug seems to be fixed. But im able to forward it and use the scrubber still which you said wont work. What exactly has changed?

**Comment by vintikzzz** [comment]
@odmivolsi  this fix only affects on-the-fly transcoded content (mkv), now you can see full timeline (full duration) for this format of content

**Comment by odmivolsi** [comment]
@vintikzzz Great! What about mp4 and other formats though?

**Comment by vintikzzz** [comment]
@odmivolsi 
.avi .mkv .flac - now show full duration, but without seeking forward
mp4 .mp3 .wav .ogg .webm - don't require transcoding (they are supported by browser out of the box), so they also have full duration and you can seek to any position
