### ISSUE TITLE
Video doesn't play even if a substantial amount is downloaded

### ISSUE THREAD

**Issue by odmivolsi** [webtor-io/player-sdk-js#12]
Sometimes the video is downloaded enough to start playing but it doesn't start and I have to refresh the page for it to start.

I have attached a screenshot where you can see that the player has downloaded enough to start playing but it still shows the thumbnail![Screenshot_20200726-020436.jpg](https://user-images.githubusercontent.com/66444874/88466181-462f5480-ceb9-11ea-8769-206ff8135f43.jpg)

**Comment by odmivolsi** [comment]
@vintikzzz

**Comment by wlasser** [comment]
I think this is core problem. I don't know how to reproduce this, but sometime webtor is very long time to "awakening".

**Comment by odmivolsi** [comment]
@wlasser yes exactly! How can this be fixed?

**Comment by wlasser** [comment]
@odmivolsi if this is exist as main core bug - there is a lot time for debugging all of over webtor stuff.
You can't do anything.
I am not developer, i can't give you any respective answer for what exactly happens.

**Comment by vintikzzz** [comment]
It really depends on current server load and their might be some ffmpeg issues during transcoding. There is no error notification at this moment, so it may look like "hanging". I am going to implement error notification this year.
