### ISSUE TITLE
Does not work on iPhone

### ISSUE THREAD

**Issue by sizzlingkenny** [webtor-io/player-sdk-js#14]
I like this streaming player and works great but only 1 problem its not working on iPhone when I open embedded player over iPhone it shows webtor.io website's index page instead of playing the file.
It seems you did not add the ios support to the player please add support for ios devices and then your player will be the best torrent streaming player in the world.

Thanks
hope this service stays online forever
long live webtor.io

**Comment by vintikzzz** [comment]
Fixed at last!!! Safari and iOS doesn't allow 3rd party cookies, so I had to make some changes...
