### ISSUE TITLE
Blank player page on chrome

### ISSUE THREAD

**Issue by odmivolsi** [webtor-io/player-sdk-js#15]
Im getting a blank page instead of the normal 'magnetising torrent' or player window.

**Comment by wlasser** [comment]
Here is two factors:
1. The torrent is not have many peers for download and webtor can't give you any stuff.
2. Main server is being shutdown or not available.

**Comment by odmivolsi** [comment]
@wlasser i am playing torrents with 1000+ seeds and they all work on firefox ,edge, etc. on both mobile and pc but chrome seems to have an issue in mobile and pc both

**Comment by vintikzzz** [comment]
Does this behaviour still exists?

**Comment by odmivolsi** [comment]
@vintikzzz yes it does

**Comment by vintikzzz** [comment]
Can you provide more details? OS, Chrome version? Does it happens with specific content? It will be great if you can provide full code of SDK initialization script

**Comment by odmivolsi** [comment]
@vintikzzz this issue has been solved on its own
