### ISSUE TITLE
How to edit headings

### ISSUE THREAD

**Issue by odmivolsi** [webtor-io/player-sdk-js#16]
Hey @vintikzzz , I want to change the headings/text that is shown on loading torrent like 'magnetising torrent' or 'seeding x MB of y MB', etc. How can I change this?

**Comment by vintikzzz** [comment]
Hi! Can you specify your use-case more detailed?
Right now you can change title of content.

**Comment by odmivolsi** [comment]
I mean that in place of 'magnetising torrent' i want to write 'making popcorn' for example

**Comment by odmivolsi** [comment]
And similarly change other titles too

**Comment by odmivolsi** [comment]
@vintikzzz please help me with this

**Comment by vintikzzz** [comment]
I can allow to override i18n-templates through sdk configuration, so you will be able to change current text and also add additional translations. Does it suits your needs?

**Comment by odmivolsi** [comment]
@vintikzzz yea i think that would work

**Comment by odmivolsi** [comment]
@vintikzzz hey man! Did you get a chance to work on this?

**Comment by vintikzzz** [comment]
@odmivolsi I have finished this, but you should wait while latest version will be available on CDN. Also look at README.md.

**Comment by odmivolsi** [comment]
@vintikzzz ok. Thanks man. How long will it take to be available on CDN?

**Comment by vintikzzz** [comment]
@odmivolsi it can take up to 12 hours according to jsDelivr docs.
But you can try latest version with this url right now:
https://cdn.jsdelivr.net/npm/@webtor/player-sdk-js@0.2.10/dist/index.min.js

**Comment by odmivolsi** [comment]
@vintikzzz thats great man!
