### ISSUE TITLE
Format not supported error

### ISSUE THREAD

**Issue by odmivolsi** [webtor-io/player-sdk-js#17]
Hello @vintikzzz , I'm getting a format not supported error. Which formats aren't supported?

**Comment by vintikzzz** [comment]
Hi!
Currently this formats are supported:
.mp4, .mp3, .wav, .ogg, .webm, .avi, .mkv, .flac, .m4a, .m4v, .png, .gif, .jpg
Waht format are you trying to play?

**Comment by odmivolsi** [comment]
Im not sure. I just played a Torrent and it said format not supported so i got curious which format aren't supported. 
Btw, we talked a few months back about powder web and you said you were trying it yourself. How's that going?

**Comment by vintikzzz** [comment]
@odmivolsi I have tried Powder Web, but I can't to start streaming (on Mac), but in case if it works there is no scaling capabilitites, so it could be ok for home usage. Powder Player works good, but there is too many alternatives to it right now uTorrent web, Soda player, Webtorrent Desktop.
