### ISSUE TITLE
Watch together feature request

### ISSUE THREAD

**Issue by odmivolsi** [webtor-io/player-sdk-js#18]
Hey @vintikzzz ! I was checking out powder web and i saw there was a feature to watch together with friends. Is this something we can do in webtor or can you please add this feature. This will be an amazing feature for webtor

**Comment by wlasser** [comment]
HLS streaming is prepared for this. I think this feature is near on future.

**Comment by odmivolsi** [comment]
@wlasser that would be great!!

**Comment by vintikzzz** [comment]
@odmivolsi can you just describe this feature in more details?

**Comment by odmivolsi** [comment]
@vintikzzz i mean that if me and my friend (both of us have an account on the website) are watching the same movie, we can watch it together. Like, if there is a text field somewhere where i can enter the ID/username of my friend and he gets a notification saying "XYZ wants to watch Avengers with you" 

or i can generate a link that i can share with my friend (on whatsapp, etc.) so that both of our movie is played together (synced playback). 

This will be like the Netflix Party extension

This is my thought, let me know what you think :)

**Comment by vintikzzz** [comment]
@odmivolsi it might be really good feature, but it is a little bit out of scope of current development, I just don't have enough time for it. So if you wish to implement something like this I can add ability to play/stop/change player position through player sdk, so it will be possbile to make sync playback.

**Comment by odmivolsi** [comment]
@vintikzzz Yes this would be an amazing feature! Webtor already has a lot of great features, this would be like icing on the cake!

Im planning to do it, it would be awesome if you allow changing position of player. 

Please let me know whenever you have time for this as i would love to develop this feature together with you. Also, can we connect on telegram?

**Comment by vintikzzz** [comment]
ok, you can find me as @vintikzzzz at telegram
