### ISSUE TITLE
Jackett integration

### ISSUE THREAD

**Issue by odmivolsi** [webtor-io/player-sdk-js#19]
@vintikzzz How do i integrate jackett or a similar Torrent search into webtor to search the correct movie/series?

**Comment by wlasser** [comment]
Hello. You are always must to have some data, forexample magnet link.
You can parse data with scripts and api of some service distribute this info.
Anyway, there is no magic buttons, you must code something.

**Comment by odmivolsi** [comment]
@wlasser yes im trying but i have no experience with jackett. I know i will have to code it myself but a little help would be wonderful :)

**Comment by odmivolsi** [comment]
@wlasser as far as i know, jackett searches for the movie/series on every possible torrent website and returns the best results.

**Comment by vintikzzz** [comment]
@odmivolsi I have already developed some library to work with jackett api, but it is in golang. If you wish I can opensource it too. There were no problems to connect webtor player sdk with jackett. So you just need to get magent-uri from jackett response and push it to player.

**Comment by odmivolsi** [comment]
@vintikzzz yes please make it open source! Thanks a lot, any help is welcome :)

**Comment by wlasser** [comment]
You can use this Python3 script for you purprose.
This require:
pip3 install bs4, requests, tornado
Affter you can run ot on defined **SERVER_PORT**, default is 8888 and you Jacket API_KEY.
Affter you can start script with python3 script_name.py, and use parsed data on adress below:
http://youhost:8888/search/Dark Knight

default view of example here: http://hyperfeed.xyz:8888/search/%D0%91%D0%BE%D0%B3%20%D0%B3%D1%80%D0%BE%D0%BC%D0%B0

You can manage you output with MainHandler function  (i am so lazy for making templates stuff), if you want you can add webtor.js here and get something.
`            for items in data:
                self.write(f"<b>File size: {bytes2human(items['size'])}</b> <a href='http://testserver:3000/play?torrent={items['magnet']}'>{items['title']}</a> - Seeders: {items['seeds']} / Peers {items['peers']} <br>")
        else:
            self.write('Nothing to found')`

```
# -*- coding: utf-8 -*-
from bs4 import BeautifulSoup
import requests as req
import tornado.ioloop
import tornado.web
import sys, asyncio

SERVER_PORT = 8888
JACKET_API_KEY = "somehash"
SEARCH_URL = "http://xxxx.xxx/api/v2.0/indexers/all/results/torznab/api?apikey="+JACKET_API_KEY+"&t=search&cat=&q="
def bytes2human(n):
    # http://code.activestate.com/recipes/578019
    # >>> bytes2human(10000)
    # '9.8K'
    # >>> bytes2human(100001221)
    # '95.4M'
    symbols = ('K', 'M', 'G', 'T', 'P', 'E', 'Z', 'Y')
    prefix = {}
    for i, s in enumerate(symbols):
        prefix[s] = 1 << (i + 1) * 10
    for s in reversed(symbols):
        if n >= prefix[s]:
            value = float(n) / prefix[s]
            return '%.1f%s' % (value, s)
    return "%sB" % n

if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

proxies = {
  'http': 'http://45.117.163.22:8080',
  'https': 'http://180.183.226.102:8080',
}

def lookuptorrent(searchquestion):
    data = []
    response = req.get(SEARCH_URL+searchquestion)
    response.encoding='utf-8'
    soup = BeautifulSoup(response.text, 'lxml')
    torrents = soup.find_all('item')
    for items in torrents:
        #print(elems)
        title = items.find('title')
        size = items.find('size')
        #seeders=int(elems.find(''))
        magnetsearch = items.find_all('torznab:attr')
        seeds = 0
        peers = 0
        for magnet in magnetsearch:
            if (magnet.get('name')=="seeders"):
                seeds = int(magnet.get('value'))
            if (magnet.get('name')=="peers"):
                peers = int(magnet.get('value'))

            if (magnet.get('name')=="magneturl"):
                data.append({'title':title.text, 'seeds':seeds, 'peers':peers, 'size': int(size.text), 'magnet':magnet.get('value')})
                #print(title.text+"\n")
                #print (magnet.get('value')+"\n")
                #print(f'Size: {size.text}\n')
                #print(f'Seeders: {seeds} Peers: {peers}\n')

    if (data):
        return data
    else:
        return None
"""
for proxy in proxies:
    response = req.get("http://222cifbta.ebg.xrutor.org/", proxies=proxy)
    if response.status_code == req.codes['ok']:
        soup = BeautifulSoup(response.text, 'lxml')
        print(soup)
        break
"""
def make_app():
    return tornado.web.Application([ (r"/search/([^/]+)", MainHandler), ])  # URL Mapping

class MainHandler(tornado.web.RequestHandler):
    SUPPORTED_METHODS = ("GET", "POST",)
    def get(self, searchQuestion):
        data = lookuptorrent(searchQuestion)
        if (data is not None):
            for items in data:
                self.write(f"<b>File size: {bytes2human(items['size'])}</b> <a href='http://testserver:3000/play?torrent={items['magnet']}'>{items['title']}</a> - Seeders: {items['seeds']} / Peers {items['peers']} <br>")
        else:
            self.write('Nothing to found')

if __name__ == "__main__":
    app = make_app()
    app.listen(SERVER_PORT)    # Port Number
    tornado.ioloop.IOLoop.current().start()

```

**Comment by vintikzzz** [comment]
@odmivolsi here is an SDK that i've promised [webtor-io/go-jackett](https://github.com/webtor-io/go-jackett)
