### ISSUE TITLE
Hide download file

### ISSUE THREAD

**Issue by risklife** [webtor-io/player-sdk-js#2]
Hello, I want to hide the message to download file, I just want to allow my users to see the torrent.

How can I do this?

**Comment by vintikzzz** [comment]
Sorry... It is a way to monetize service and pay for servers. You can always switch to [platform-sdk](https://github.com/webtor-io/platform-sdk-js) and host webtor api by yourself, so, in this case, you can customize it as you wish. There could be some exception anyway, feel free to contact me via the [support form](https://webtor.io/support)

**Comment by risklife** [comment]
I think that you can monetize with the player, is better, and offer the option for hide the download label.

**Comment by vintikzzz** [comment]
If you have specific ideas just contact me directly. It is not the best place to discuss monetization strategies of my service.
