### ISSUE TITLE
Playing a video without a server

### ISSUE THREAD

**Issue by marekduse** [webtor-io/player-sdk-js#20]
Hello,

Is it possible to configure without an external server? Here, from what I see playing video when external server start downloading torrent. Is it possible to download directly? So when the user starts playing, he downloads via torrent in the background and seed.

Thanks for answer.

**Comment by vio-codes** [comment]
I think you are looking for something else in this case, like https://instant.io/ based on webtorrent

**Comment by wlasser** [comment]
as @vio-codes mentioned - you are looking something like torrent client for java, this available just with WEB-RTC/webtorrent protocol, but this not have ability to work with normal bittorents client, just webtorrent.

**Comment by vintikzzz** [comment]
@wlasser @vio-codes thanks for answers. You are right there.
@marekduse there is no way for web-browser to communicate with bittorent-peers without additional extensions and plugins. I really don't think that any mainstream browser will natively support bittorrent network in the future.
