### ISSUE TITLE
Doesn't see any related changes, but embed player loose playlist

### ISSUE THREAD

**Issue by wlasser** [webtor-io/player-sdk-js#22]
Hello @vintikzzz !

I am using next code to integrate with website, but now player load first file, and don't give a ability to select other.
I am look over last changes, but don't see options/settings for this in player js sdk.
```
<script>
        window.webtor = window.webtor || [];
        window.webtor.push({
            id: 'player',
            magnet: 'magnet:?xt=u',
            on: function(e) {
                if (e.name == window.webtor.TORRENT_FETCHED) {
                    console.log('Torrent fetched!')
                }
                if (e.name == window.webtor.TORRENT_ERROR) {
                    console.log('Torrent error!')
                }
            },
        });
    </script>
```

**Comment by vintikzzz** [comment]
Hi!
It is possible to select specific file by providing `pwd` and `file` parameter.
Also it is possbile to use player API to select another file after player initialization.
You can check out full example [here](https://webtor.io/sdk-example.html)
Also there will be an option to select another file inside player soon.

**Comment by wlasser** [comment]
Oh ok, thanks.
