### ISSUE TITLE
Opensubtitles not working in sdk embed.

### ISSUE THREAD

**Issue by redehaka** [webtor-io/player-sdk-js#23]
opensubtitles not working in embed player. Also h265 not work. Can you support h265?

**Comment by vintikzzz** [comment]
Please provide example url to webtor service and check before if there any subtitles for this movie at OpenSubtitles.
I can't support h265 right now. I am going to provide longterm caching for transcoded content this year, then I will check resource consumption and if there will be enough I will enable h265. If you are strong enough to become Generous Backer via Patreon, then I can enable h265 right now. Keep in mind that conversion from h265 to h264 is quite resource consumption task and I will use very optimized ffmpeg settings to perform near realtime transcoding, so image quality will become really poor. I can try to use some GPU-involved transcoding to achive better quality, but price of virtual servers with GPU are really high. If you want realtime transcoding with good quality so there should be more donations to cover server costs. If you have already such server that you can give away for transcoding just let me know. In other cases just try to find content without h265 encoding.

**Comment by redehaka** [comment]
https://big-boss-cinema.com/movies/greenland/
Click on tab "гледай онлайн"/watch online/ and you see webtor player as first, now you can see opensubtitles not found subs, but movie have - https://www.opensubtitles.org/search/sublanguageid-all/idmovie-920869

**Comment by vintikzzz** [comment]
ok, just change imdb setting from 'tt7737786' to '7737786', I think I need to support both variants of imdb id.

**Comment by redehaka** [comment]
Yes support both variants is the best solution, I just not use this feature now, cannot change this because is automatically set from tmdb api used in dooplay dbmvs, 90 % of movies streaming themes and scripts used tmdb api and imdb Id is with tt.

**Comment by vintikzzz** [comment]
Now it will support both variants.
![image](https://user-images.githubusercontent.com/150981/100515993-a39e1f80-3191-11eb-847e-22feadd15adc.png)
