### ISSUE TITLE
Automatic Choose Subtitle from pushed subtitle

### ISSUE THREAD

**Issue by hsnfirdaus** [webtor-io/player-sdk-js#25]
Hi, so can you add feature to automatic choose subtitle from pushed subtitle url. Becuase, when beginning, subtitle automatic chose none.

**Comment by ilirkl** [comment]
i would like this too

**Comment by vintikzzz** [comment]
special `autoselect: true` subtitle attribute will do the trick

**Comment by ExPlayer21** [comment]
@vintikzzz как с Вами связаться (обратная связь на сайте webtor.io не работает)? Или подскажите, в чем может быть проблема: ни одно видео не воспроизводится, постоянно появляется сообщение "Видео на данный момент недоступно, пожалуйста попробуйте позднее...", причем не зависимо от количества пиров.
