### ISSUE TITLE
Corrupted zip archive 

### ISSUE THREAD

**Issue by devsynck** [webtor-io/player-sdk-js#26]
While downloading partial content from torrent, zip archive getting corrupted.

**Comment by vintikzzz** [comment]
Hi! I need an example.

**Comment by devsynck** [comment]
Assume a torrent have multiple folders and user want to download only one of that folder as zip instead of whole torrent. In that case zip downloads but while opening it shows corrupted.

**Comment by vintikzzz** [comment]
Do you have some specific unarchiver?

**Comment by devsynck** [comment]
I'm using 7zip. Btw, great project ! Very useful.

**Comment by vintikzzz** [comment]
Can you recheck? If you will see some CRC32-errors, just ignore them.

**Comment by devsynck** [comment]
It works now, Thanks !
