### ISSUE TITLE
Not working with browsers with single window(tab) 

### ISSUE THREAD

**Issue by LexPowerMetal** [webtor-io/player-sdk-js#29]
Tesla browsers doesn't hava multi windows (tabs). I think there was a change in code, where before ads would open in popups. Now when I press play, the ad opens in new window. It's not a problem if your browser supports tabs. But as mentioned above, Tesla browser doesn't support multi tabs, hence the ad opens in the same window. When I press back it goes to previous window. When I press Play, it opens ad in the same window. Would it be possible to fix? As it was working fine few weeks ago.

https://user-images.githubusercontent.com/79021433/107859364-fdc58d00-6e30-11eb-9cf3-c910a7abed9d.mp4

**Comment by vintikzzz** [comment]
I have just switched to another ad network for test. I suppose, new ad network doesn't have any capping right now. Furthermore, I have already asked to add it. If they will not be able to set it, I will add capping from my side.

**Comment by vintikzzz** [comment]
Should be fixed... Can you check?

**Comment by LexPowerMetal** [comment]
Looks like if I play torrent from webtor.io, it works fine, so it's fixed. But if I try to play from yor player, but hosted on my own website it is doing the same thing. Do I need to update code or something? 

https://user-images.githubusercontent.com/79021433/107982785-92102b00-6fbc-11eb-8b44-8746bebee8e8.mp4

**Comment by vintikzzz** [comment]
No, all fixed on my side. You don't have to update anything.

**Comment by LexPowerMetal** [comment]
Hi again. It worked for a few days and now I can't get it to work as same problem priciests. I can go back and forth like 20 times, but it still will go to adverts page when I press "Play" button.
