### ISSUE TITLE
Error with fetching torrent

### ISSUE THREAD

**Issue by wlasser** [webtor-io/player-sdk-js#3]
Hello Webtor.
Just trying to include player on my page, but has no luck with it.
Getting "torrent error" on any magnet.
Live example doesn't work too.
Any solution/suggestion?

**Comment by vintikzzz** [comment]
Hmmm... I have tested all today, everything works fine.
Are you using some proxy or vpn? Sometimes it cuts websockets...

**Comment by wlasser** [comment]
> Hmmm... I have tested all today, everything works fine.
> Are you using some proxy or vpn? Sometimes it cuts websockets...

No. No proxy or VPN.
Well... Affter disabling adblock player is start do job. Thanks for advice.

**Comment by vintikzzz** [comment]
Did you manage it? What was the cause?

**Comment by wlasser** [comment]
> Did you manage it? What was the cause?

Disabling adblock is help me. But now i am see new trouble - early version of webtor (i mean webtor.io) is working good with playing torrents. But now playing freezing too many. My connection is 70 mbit. Before with 10 mbit all is being good.

**Comment by vintikzzz** [comment]
Yes. I have now very strict traffic limits per stream/download (around 0.7Mbps for non-sponsors). There were more users than I can handle. But it is a thing of the past and I will increase limits to 3Mbps today. Just check it )

**Comment by wlasser** [comment]
> Yes. I have now very strict traffic limits per stream/download (around 0.7Mbps for non-sponsors). There were more users than I can handle. But it is a thing of the past and I will increase limits to 3Mbps today. Just check it )

Best news for today. 
I want to host my own webtor instance, but too many new things for me: minukube, helm-charts... 
I think the future of internet is projects like webtor. Thanks for you work.
