### ISSUE TITLE
how to use torrentUrl?

### ISSUE THREAD

**Issue by foxerbg** [webtor-io/player-sdk-js#32]
can someone tell me how to play a torrent file using torrentUrl. When i run my code i got this "Preparing Video Stream... Please Wait..."
i include  header('Access-Control-Allow-Origin: *');  with php 
Here is my code
`
<?php header('Access-Control-Allow-Origin: *'); ?>

    <div id="player" class="webtor" />
    <script>
        window.webtor = window.webtor || [];
        window.webtor.push({
            id: 'player',
            torrentUrl: 'test.torrent',
            on: function(e) {
                if (e.name == window.webtor.TORRENT_FETCHED) {
                    console.log('Torrent fetched!', e.data);
                }
                if (e.name == window.webtor.TORRENT_ERROR) {
                    console.log('Torrent error!');
                }
            },
            poster: 'https://via.placeholder.com/150/0000FF/808080?Text=Sintel',
            subtitles: [
                {
                    srclang: 'en',
                    label: 'test',
                    src: 'https://raw.githubusercontent.com/andreyvit/subtitle-tools/master/sample.srt',
                }
            ],
            lang: 'en',
            i18n: {
                en: {
                    common: {
                        "prepare to play": "Preparing Video Stream... Please Wait...",
                    },
                    stat: {
                        "seeding": "Seeding",
                        "waiting": "Client initialization",
                        "waiting for peers": "Waiting for peers",
                        "from": "from",
                    },
                },
            },
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@webtor/player-sdk-js/dist/index.min.js" charset="utf-8"></script>
`

**Comment by vintikzzz** [comment]
Hi @foxerbg ! Maybe you just need to put full absolute url to the torrent? It doesn't work with local urls.

**Comment by foxerbg** [comment]
> Hi @foxerbg ! Maybe you just need to put full absolute url to the torrent? It doesn't work with local urls.

i tried with full link 'https://zamunda.net/download.php/643074/Superintelligence.2020.WEBRip.x264.AAC-HUD.torrent' but sttill not working ..

**Comment by vintikzzz** [comment]
```
% curl 'https://zamunda.net/download.php/643074/Superintelligence.2020.WEBRip.x264.AAC-HUD.torrent' -v
*   Trying 172.67.211.73...
* TCP_NODELAY set
* Connected to zamunda.net (172.67.211.73) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=zamunda.net
*  start date: Jun 21 00:00:00 2020 GMT
*  expire date: Jun 21 12:00:00 2021 GMT
*  subjectAltName: host "zamunda.net" matched cert's "zamunda.net"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fba7280dc00)
> GET /download.php/643074/Superintelligence.2020.WEBRip.x264.AAC-HUD.torrent HTTP/2
> Host: zamunda.net
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 302
< date: Thu, 25 Mar 2021 11:34:49 GMT
< content-type: text/html; charset=UTF-8
< set-cookie: __cfduid=d5cf27576245e13c309e6c8742fe2c12b1616672089; expires=Sat, 24-Apr-21 11:34:49 GMT; path=/; domain=.zamunda.net; HttpOnly; SameSite=Lax
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
< location: /login.php?returnto=%2Fdownload.php%2F643074%2FSuperintelligence.2020.WEBRip.x264.AAC-HUD.torrent
< cf-cache-status: BYPASS
< cf-request-id: 090ac37d060000bd9b98b53000000001
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< set-cookie: PHPSESSID=5cng9bcj2onrgjotb8qrmo1rop; path=/
< set-cookie: goe=RU; expires=Fri, 26-Mar-2021 11:34:49 GMT; Max-Age=86400; path=/; domain=.zamunda.net
< set-cookie: russian_lang=yes; expires=Fri, 26-Mar-2021 11:34:49 GMT; Max-Age=86400; path=/; domain=.zamunda.net
< set-cookie: __cf_bm=3603dda2e85364241ed138b2fe6ad88c9f106020-1616672089-1800-AQUEE8plNdcaxC2vXAzOrKRLVODN9TdrMeBS1wd3CcMXss3cRihB4EW64ava62GPaBwhU/mGZQIObRUbYVIWCo4=; path=/; expires=Thu, 25-Mar-21 12:04:49 GMT; domain=.zamunda.net; HttpOnly; Secure; SameSite=None
< report-to: {"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=%2FQi2uBlmjF92spQGU0XbJTuXu9EUddP7gyQrt1vcGyZ4Bz94He8bM4BwmgCnsjYYgdryja2DO%2FN5WOvYQuBJtat1F5aynwIOblUUOA%3D%3D"}],"max_age":604800}
< nel: {"max_age":604800,"report_to":"cf-nel"}
< server: cloudflare
< cf-ray: 6357d50e6f8dbd9b-AMS
< alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
<
* Connection #0 to host zamunda.net left intact
* Closing connection 0
```
As you can see here, server returns redirect to login page instead of torrent. Torrent **MUST** be public available.

**Comment by foxerbg** [comment]
so there is no way i can bypass this login even if i have a passkey?

**Comment by vintikzzz** [comment]
So you can download it and then put somewhere to make it public available.

**Comment by foxerbg** [comment]
i was trying to make it automatic to get file and play it form RSS i cant even make it download. Maybe i will look for other solution.
