### ISSUE TITLE
Player not working on iOs safari 

### ISSUE THREAD

**Issue by AdiGaikwad** [webtor-io/player-sdk-js#34]
Player does not work on iphone and ipad safari 

  window.webtor = window.webtor || [];
        window.webtor.push({
            id: 'player',
            magnet: `magnet:?xt=urn:btih:${param.th}&dn=${param.mn}`,
            on: function(e) {
                if (e.name == window.webtor.TORRENT_FETCHED) {
                    console.log('Torrent fetched!', e.data);
                }
                if (e.name == window.webtor.TORRENT_ERROR) {
                    console.log('Torrent error!');
                }
            },
            poster: imagePath,
            subtitles: [

            ],
            lang: 'en',
            i18n: {
                en: {
                    common: {
                        "prepare to play": "Preparing Video Stream... Please Wait...",
                    },
                    stat: {
                        "seeding": "Seeding",
                        "waiting": "Client initialization",
                        "waiting for peers": "Waiting for peers",
                        "from": "from",
                    },
                },
            },
        });

**Comment by vintikzzz** [comment]
Please provide final script without variables

**Comment by AdiGaikwad** [comment]
window.webtor = window.webtor || [];
window.webtor.push({
id: 'player',
magnet: magnet:?xt=urn:btih:227F05638D05C6798B4D86E34429FB7D34474576&dn=godzilla-vs-kong-2021,
on: function(e) {
if (e.name == window.webtor.TORRENT_FETCHED) {
console.log('Torrent fetched!', e.data);
}
if (e.name == window.webtor.TORRENT_ERROR) {
console.log('Torrent error!');
}
},
poster: imagePath,
subtitles: [

        ],
        lang: 'en',
        i18n: {
            en: {
                common: {
                    "prepare to play": "Preparing Video Stream... Please Wait...",
                },
                stat: {
                    "seeding": "Seeding",
                    "waiting": "Client initialization",
                    "waiting for peers": "Waiting for peers",
                    "from": "from",
                },
            },
        },
    });

**Comment by vintikzzz** [comment]
magnet:?xt=urn:btih:227F05638D05C6798B4D86E34429FB7D34474576&dn=godzilla-vs-kong-2021 should be in quotes like so
```
magnet: 'magnet:?xt=urn:btih:227F05638D05C6798B4D86E34429FB7D34474576&dn=godzilla-vs-kong-2021',
```
You can also check [Basic usage](https://github.com/webtor-io/player-sdk-js#basic-usage)

**Comment by AdiGaikwad** [comment]
Tried that still not working

**Comment by AdiGaikwad** [comment]
Even main webtor.io website does not work on iOs devices (with above torrent hash)

**Comment by vintikzzz** [comment]
Just checked it from Safari on iOS 14.4.2
![image](https://user-images.githubusercontent.com/150981/114906411-accb1880-9e22-11eb-9dde-47718e6b9378.png)

**Comment by AdiGaikwad** [comment]
Ok I will check again using a VPN tomorrow

**Comment by AdiGaikwad** [comment]
![20210416-074640](https://user-images.githubusercontent.com/64576596/114962540-79bb7000-9e88-11eb-88c6-8d83a9d0640c.jpg)

Tried on Ipad pro 9.7 inch software version 13.6.1

Does not work

**Comment by AdiGaikwad** [comment]
Ok I checked in iOs 14.3 and it worked smoothly
I think there is a problem with iOs 13

**Comment by vintikzzz** [comment]
I have also tried on iPad with iOS 14.4.2 and there were no problems. I currently have no devices with iOS 13 to reproduce this issue. Can you just update iOS version?

**Comment by AdiGaikwad** [comment]
Yep that's what I am doing thank you for your help 🙂
