### ISSUE TITLE
Selected file in torrent in selected directory not working!

### ISSUE THREAD

**Issue by redehaka** [webtor-io/player-sdk-js#36]
I use file Player configuration Attribute and working fine before, but now not working it's show only first video file!

<div id="player" class="webtor" />
    <script>
        window.webtor = window.webtor || [];
        window.webtor.push({
            id: 'player',
			width: '100%',
            magnet: 'magnet:?xt=urn:btih:a5798e1d8641b2d11f9b124f47cda24fc94b62d5',
            on: function(e) {
                if (e.name == window.webtor.TORRENT_FETCHED) {
                    console.log('Torrent fetched!')
                }
                if (e.name == window.webtor.TORRENT_ERROR) {
                    console.log('Torrent error!')
                }
            },
            poster: 'https://zamunda.net/pic/img4/bitbucket/412933/1613722645_2610928.jpg',
            
            file: 'Tell.Me.Your.Secrets.S01E04.720p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv',
            subtitles: [
                {
                    srclang: 'Bulgarian',
                    label: 'Български',
                    src: '',
                    autoselect: true,
                }
            ],
			
            features: {
    p2pProgress: true,
    title:       true,
    settings:    true,
    fullscreen:  true,
    subtitles:   true,
    continue:    true,
    playpause:   true,
    currentTime: true,
    timeline:    true,
    duration:    true,
    volume:      true,
    chromecast:  true,
    browse:      true,
    download:    true,
}
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@webtor/player-sdk-js/dist/index.min.js" charset="utf-8" async></script> 
    </div>
 </div> 

And this is [results](http://big-boss-online.do.am/offline/new_issue_webtor-io_player-sdk-js.html)

**Comment by vintikzzz** [comment]
Fixed! You can check your [example](http://big-boss-online.do.am/offline/new_issue_webtor-io_player-sdk-js.html).

**Comment by redehaka** [comment]
Yes now work, thanks
