### ISSUE TITLE
Video not start when is converted on Android.

### ISSUE THREAD

**Issue by redehaka** [webtor-io/player-sdk-js#38]
When file is not mp4 and start converted, video not start to play in Android. Just poster seen on screen. Tested on Android 8.1 and 10, with chrome and opera. If file is mp4 video start and play.

**Comment by redehaka** [comment]
Demo https://youtu.be/mMRj7AnJafk

**Comment by vintikzzz** [comment]
Fixed
@redehaka may you recheck?

**Comment by redehaka** [comment]
Yes now working
