### ISSUE TITLE
Progressbar just showing loaded pieces

### ISSUE THREAD

**Issue by wlasser** [webtor-io/player-sdk-js#4]
I am read over last Webtor updates and found something about this, but early version is have full progressbar with abilty to scroll to any place of streaming video.
Now this feature is dead.
Maybe you can review something?

**Comment by wlasser** [comment]
Is anyway to embed two or many player instance on the page?

**Comment by vintikzzz** [comment]
Scrolling to any place of the video was removed only for transcoding. You can read more about it in [release notes for version 1.6.0](https://blog.webtor.io/en/post/new-features-in-webtor-1.6.0/).
You can embed as many players as you like on web page, just use elements with unique ids to place player.

**Comment by wlasser** [comment]
> Scrolling to any place of the video was removed only for transcoding. You can read more about it in [release notes for version 1.6.0](https://blog.webtor.io/en/post/new-features-in-webtor-1.6.0/).
> You can embed as many players as you like on web page, just use elements with unique ids to place player.

well, something i can missunderstand, but have no luck with it. 
try to push new player webtor.webtor with new player id, but player is load just last torrent in array in both player elements.

**Comment by vintikzzz** [comment]
I need some time to check it!

**Comment by wlasser** [comment]
@vintikzzz Is you look over this? Do we have ability to use player embed more than one frame per page?

**Comment by vintikzzz** [comment]
@wlasser I have fixed multiple embeding
You can check it here https://jsbin.com/jayicihote/1/edit?html,output
