### ISSUE TITLE
torrent wont load in react with innerhtml

### ISSUE THREAD

**Issue by DanielTangnes** [webtor-io/player-sdk-js#40]
the player works fine with html, but when i run it in react i get an error saying "net::ERR_UNKNOWN_URL_SCHEME".
![image](https://user-images.githubusercontent.com/66026708/119735690-02143400-be7d-11eb-9d7d-d94a1e1490ee.png)
![image](https://user-images.githubusercontent.com/66026708/119735750-13f5d700-be7d-11eb-93f0-c6663e0290f6.png)

**Comment by vintikzzz** [comment]
Hi! It looks like "basic usage" doesn't works well here, just check "advanced usage" and #28
