### ISSUE TITLE
how can i hide the control buttons?...

### ISSUE THREAD

**Issue by Nymka-9229** [webtor-io/player-sdk-js#43]
how can i hide the control buttons?... i want to disable and hide some of the control buttons in player. How can i do that?

**Comment by vintikzzz** [comment]
It really depends if you follow "basic" or "advanced" usage.
In "advanced" to disable feature just put it in `features` object this way:
```javascript
    features: {
        subtitles:    false,
    },
```
https://jsbin.com/vogike/edit?html,output - live example

In "basic" just put the same in `data-features` attribute :
```html
<video controls src="magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel" data-features='{"subtitles": false}' />
```
https://jsbin.com/lekuzez/edit?html,output - live example

https://github.com/webtor-io/embed-sdk-js#player-features - list of all available features
