### ISSUE TITLE
subtitle is not visible on mobile device when player is on fullscreen mode

### ISSUE THREAD

**Issue by Nymka-9229** [webtor-io/player-sdk-js#44]
At first, it's fine with mobile device, everything is ok and subtitles are visible but when i turn on fullscreen mode player is not showing subtitles, then when i turn off fullscreen mode subtitles are visible but in so small size, i can see it barely. And also, timeline is not hidden, it's always visible and covering subtitles in mobile device. It's so annoying, Please fix this issue..
my email address: nymjargal9229@gmail.com

**Comment by vintikzzz** [comment]
Hi! Please provide information about what mobile device are you using. Also share example code where you had issues.
