### ISSUE TITLE
Edit Player UI

### ISSUE THREAD

**Issue by diivi** [webtor-io/player-sdk-js#45]
If I were to edit the player's UI, how would I go about doing so? I can't find any css files in the source code and the player looks a little different from the default mediaplayer.js player.
I want to personalise it / make it look and feel a little better, either by using an API or forking and editing the code myself, thanks.

**Comment by diivi** [comment]
Hey, I have made it look a little better.
Just one more question though, are you limiting download speeds for non sponsorers in the SDK?

**Comment by vintikzzz** [comment]
Hi @diivi 
limits are all controlled by backend part.

**Comment by diivi** [comment]
any way I can work with the media-element.js api inside this sdk? @vintikzzz 
Also, thanks for working on this, really helps in a project that I am making, I will give you credits fwiw

**Comment by diivi** [comment]
![image](https://user-images.githubusercontent.com/41837037/126839277-eea61c86-57f0-4df1-9a62-2be205e7dc6f.png)
Also, I am not able to access the player methods even after the first play-click. Any idea why this is happening?

**Comment by vintikzzz** [comment]
can you share full example somewhere?

**Comment by diivi** [comment]
https://codepen.io/divi7/pen/eYWeexe try using webtor methods in the console

**Comment by vintikzzz** [comment]
it doesn't work this way, check https://webtor.io/sdk-example.html, especially these lines:
```javascript
if (e.name == window.webtor.INITED) {
    var p = e.player;
    document.getElementById('play').addEventListener('click', function(ev) {
        p.play();
    });
    document.getElementById('pause').addEventListener('click', function(ev) {
        p.pause();
    });
    document.getElementById('moveto1min').addEventListener('click', function(ev) {
        p.setPosition(60);
    });
    document.getElementById('movetostart').addEventListener('click', function(ev) {
        p.setPosition(0);
    });
}
```
As you can see you need to wait for specific event `window.webtor.INITED` and get `e.player` that provides player API methods.

It may look not so straightforward at the first glance, but it gains you the ability to put multiple players on the page and control them separately.
