### ISSUE TITLE
iFrameSizer memory leak

### ISSUE THREAD

**Issue by edwinork** [webtor-io/player-sdk-js#49]
I use Webtor embed with React in a single-page application. For this reason, the element that contains Webtor iframe gets deleted and re-created often. I noticed that after each delete, iFrameResizer floods the console with messages if window gets resized. After investigation, I found that it keeps listeners for all Webtor iframes that ever existed. Please see this [demo of the issue](https://codesandbox.io/s/webtor-iframesizer-issue-elctq?file=/src/App.tsx).

I looked around at iFrameResizer code and found a possible solution. It exposes a ```close``` method which cleans up all of the listeners and removes the referenced iframe element. I think there are couple of possible ways to use this:
- During ```webtor.push``` add a mutation observer and do the iFrameResizer clean-up when iframe is removed from DOM
- Expose something like ```webtor.close``` which users of embed-sdk-js would have to call manually when clean-up is needed

Or is there already a way to clean-up and I missed it?

**Comment by edwinork** [comment]
[I just found another listener that doesn't get cleaned up](https://github.com/webtor-io/embed-sdk-js/blob/388e5c38457aba58a8d37b9c17d9769fee1d4bfe/src/webtor/WebtorGenerator.js#L104). It's a minor issue because of ```id``` check so nothing gets executed for every single Webtor embed that ever existed. I thought I'd still mention it in this ticket because it could be cleaned up in the same spot as iFrameResizer listeners.

**Comment by vintikzzz** [comment]
@edwinork thank you for investigation and great insights, I will check it this week
