### ISSUE TITLE
Advertising on Webtor

### ISSUE THREAD

**Issue by urltv** [webtor-io/player-sdk-js#50]
Is there a possibility to have an ad-free player?
Or is it the indirect way to stimulate the payment of money to your project?
I think the one you provide is an excellent service, but I try to use it in Samsung's Tizen browser, which doesn't support extensions like Adblock, and I can't watch a movie without the same Webtor.io player showing me pornographic or product advertisements. random, for the same reason I ask again, is there a way to have a clean version of the code?

**Comment by vintikzzz** [comment]
Hi @urltv
You can always [become a patron](https://www.patreon.com/bePatron?u=24145874) of webtor to remove ads, also starting from "Silver Backer" it is possible to use webtor embed without ads on specific domain. There are only two steps to do this:
1. Become a "Silver Backer"
2. Send me a message at Patreon with your domain name

**Comment by urltv** [comment]
Why did you mark me as spam? Now they blocked my account -_-
what is your problem

**Comment by vintikzzz** [comment]
@urltv Hi! Can you share your account name at Patreon?
Why I added a few users to Spam: earlier at Patreon it was possible to become a backer without any payment at first month (payment was retrieved only next month). And some users used that feature, so they got maximum tier, used all benefits all month and then just declined payment.
