### ISSUE TITLE
subs auto select/start

### ISSUE THREAD

**Issue by foxerbg** [webtor-io/player-sdk-js#51]
hello, how can i make subs auto start here is my code but not working, its working only if i choose manual the subs.

`<script>
        window.webtor = window.webtor || [];
        window.webtor.push({
            id: 'player',
			magnet: 'magnet:?xt=urn:btih:<?php echo $player; ?>',
			width: '100%',
            on: function(e) {
                if (e.name == window.webtor.TORRENT_FETCHED) {
                    console.log('Torrent fetched!', e.data);
                }
                if (e.name == window.webtor.TORRENT_ERROR) {
                    console.log('Има проблем, моля те докладвай го този филм!');
                }
            },
            poster: 'https://www.filmite-bg.com/poster.jpg',

            subtitles: [
			{
                    srclang: 'bg',
                    label: 'Български',
                    src: 'url-to-my-subs',
                }
				
            ],
			
			
			
			  features: [
                {
                        p2pProgress: true,
    title:       false,
    settings:    true,
    fullscreen:  true,
    subtitles:   true,
    continue:    true,
    playpause:   true,
    currentTime: true,
    timeline:    true,
    duration:    true,
    volume:      true,
    chromecast:  true,
    browse:      false,
    download:    true,
                }
            ],
	
            lang: 'en',
            i18n: {
                en: {
                    common: {
                        "prepare to play": "Зареждаме видеото... Моля за търпение...",
                    },
                    stat: {
                        "seeding": "Сиидваме",
                        "waiting": "Свързване",
                        "waiting for peers": "Чакаме за пиъри",
                        "from": "От",
                    },
                },
            },
        });
		
    </script>`

**Comment by foxerbg** [comment]
will i  get answer?

**Comment by vintikzzz** [comment]
Please check documentation https://github.com/webtor-io/embed-sdk-js#subtitle-configuration
