### ISSUE TITLE
Webtor sdk is not working in mobile device

### ISSUE THREAD

**Issue by Nymka-9229** [webtor-io/player-sdk-js#52]
webtor sdk is not working on mobile device. It just responds like "video not available right now. try again later". Please fix this issue quickly.
![Screenshot_2021-10-02-22-59-55](https://user-images.githubusercontent.com/85881525/135722183-47dbc507-9ab0-437e-873f-55c2f5940ab7.png)

**Comment by vintikzzz** [comment]
@Nymka-9229 Please provide url to check and model of your mobile device. Also provide how did you initialize SDK.

**Comment by yzqiang666** [comment]
me too

**Comment by vintikzzz** [comment]
@yzqiang666 Please provide url to check and model of your mobile device. Also provide how did you initialize SDK.

**Comment by sorryjack** [comment]
I have the same issue. the player loading in phone, used brave browser, click play, then 1 second sound but no video, then it likes the player is gone. just blank, with nothing. tried via browser, no sound, no play button. please help how to solve this.
here is my codes in attachment
![image](https://user-images.githubusercontent.com/6811578/146112534-54f3537a-0d9d-45db-858a-a51f24907fab.png)
site url is [https://movienade.com](https://movienade.com)

**Comment by tigranmamikonyan** [comment]
Same problem here only audio plays. https://webtor.io/#/show?file=Memory.2022.Pk.TS.14OOMB.avi&pwd=%2F&magnet=magnet%3A%3Fxt%3Durn%3Abtih%3A9075078f41500544ddeb32c497580c0b683406e9%26dn%3DMemory.2022.Pk.TS.14OOMB.avi%26tr%3Dhttp%253A%252F%252Fultradox.site%253A2710%252Fannounce%26tr%3Dudp%253A%252F%252F9.rarbg.me%253A2970%252Fannounce%26tr%3Dudp%253A%252F%252F9.rarbg.to%253A2960%252Fannounce%26tr%3Dhttp%253A%252F%252Fopentracker.i2p.rocks%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.opentrackr.org%253A1337%252Fannounce%26tr%3Dhttp%253A%252F%252Ftracker.opentrackr.org%253A1337%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.internetwarriors.net%253A1337%252Fannounce&event=player-logo-click
