### ISSUE TITLE
Webtor Video is not played

### ISSUE THREAD

**Issue by daoquangphuong** [webtor-io/player-sdk-js#53]
The video player disappear after click play for a while.
here is the magnet link to check:

magnet:?xt=urn:btih:2bdeb90d24221269ffc64058c814212bda354ca0

error shows at inspect: 
Uncaught (in promise) DOMException: Failed to load because no supported source was found.

**Comment by vintikzzz** [comment]
Hi! h265 (HEVC) codec in mp4 container is not supported right now. You currently can only download it.

**Comment by benjaminkovacevic** [comment]
https://www.1377x.to/torrent/5195642/Diabolik-2021-BluRay-1080p-H264-Ita-AC3-5-1-Sub-Ita-Eng-realDMDJ-iDN_CreW/

Whats up with this one? Its h264 and image is still black
