### ISSUE TITLE
Unable to load torrent-file!

### ISSUE THREAD

**Issue by ghost** [webtor-io/player-sdk-js#55]
Whenever I try to paste magnet link or open torrent file, it says "Unable to load torrent-file! Try to load torrent-file with "Open torrent online button" ". It happens when I use 1DM or any other download manager with browser on Android but not when I use Firefox. Any way to fix it? I don't want to use Firefox because it doesn't support resume downloads. Last time I used this website was like 2 weeks ago and was working fine with 1DM.

**Comment by vintikzzz** [comment]
Can you share your magnet url that you are unable to paste?

**Comment by ghost** [comment]
As I said, it works with any torrent on Firefox but not on download managers

1DM screenshot:
https://imgur.com/a/CdwGnlw
Firefox screenshot:
https://imgur.com/a/M6wfXOE

**Comment by vintikzzz** [comment]
Are we talking about android phone not desktop? Have you tried Chrome?

**Comment by ghost** [comment]
Looks like Chrome works, I didn't know that it had resume option. Thanks!
