### ISSUE TITLE
Cant get player currentTime and other controls

### ISSUE THREAD

**Issue by Suleiman700** [webtor-io/player-sdk-js#56]
Im trying to use some commands on the player like

- currentTime
- play
- pause

the commands will return null unless I use inspect elements

the upper command before using inspect element, and the bottom one after using inspect element

![chrome_lff76xOnG1](https://user-images.githubusercontent.com/25286081/140336398-b513ef67-d373-4e16-ba12-3bd387c29c4a.png)

Commands I'm trying (works after inspect elements only)
![chrome_nY3uo9FG58](https://user-images.githubusercontent.com/25286081/140336600-de10faca-4007-4dce-b167-ae13918b06f5.png)

**Comment by vintikzzz** [comment]
This will not work, use documentation:
https://github.com/webtor-io/embed-sdk-js#player-events

**Comment by Suleiman700** [comment]
can you help me with this ?
will it even work ?

**Comment by vintikzzz** [comment]
https://webtor.io/sdk-example.html - check an example

**Comment by Suleiman700** [comment]
THANKS A LOT MY FRIEND
this helped me so much
