### ISSUE TITLE
'Download at webtor' logo above controls

### ISSUE THREAD

**Issue by FurkanSimsir** [webtor-io/player-sdk-js#62]
The z-index of the 'download at webtor' logo on the bottom left is higher than the z-index of the controls. This is particularly annoying on mobile devices because it blocks the user from selecting a subtitle. Is it possible to fix this and/or hide the 'download at webtor' logo?

**Comment by vintikzzz** [comment]
Fixed!

**Comment by twitchk** [comment]
How did you fix it pls?
