### ISSUE TITLE
Player not start when host index.min.js on my server

### ISSUE THREAD

**Issue by beshoo** [webtor-io/player-sdk-js#63]
Why I can not host the index.min.js on my CDN website?

Regards

**Comment by vintikzzz** [comment]
Hi! Webtor monetizes itself by serving ads. Any modifications to embed sdk script can lead to revenue loss. To prevent such modifications webtor checks source of embed script to be original.

**Comment by beshoo** [comment]
The problem is the type of ads, it is popup full of sexual content, if you
make the ads like YouTube, when the vedio starts and user can escape the
ads it will be more elegant.

But popup is the worst option to go with.

Any way, is there any one time fee that we can pay to remove the ads.?
Regard

**Comment by vintikzzz** [comment]
I know that it's not the best option for user experience, but I haven't found any better way so far. If you know any ad network that could provide better variants with good CPM just let me know.

You may start to support project (5$ every month or more) and I will remove ads for your domain.

https://www.patreon.com/bePatron?u=24145874 - donation link

**Comment by beshoo** [comment]
Why dont use adsense.
Seconds, am looking for one time payment.

And unlimited useg.

Regard

**Comment by vintikzzz** [comment]
> Why dont use adsense.

AdSense can't work in iframe (in embed) and I use it on main site already.

> Seconds, am looking for one time payment.
And unlimited useg.

Oh, sorry, I can't help you here. But you can setup and host webtor api by yourself. Check this [docs](https://github.com/webtor-io/helm-charts) for more information.

**Comment by gocejov** [comment]
> I know that it's not the best option for user experience, but I haven't found any better way so far. If you know any ad network that could provide better variants with good CPM just let me know.
> 
> You may start to support project (5$ every month or more) and I will remove ads for your domain.
> 
> https://www.patreon.com/bePatron?u=24145874 - donation link

i started donate you 5$ montly but the ads where removed only for my gmail account, but not for the entire domain. Can you please help me on this ?
@vintikzzz

**Comment by vintikzzz** [comment]
@gocejov please send me direct message through Patreon with yout site domain name.

**Comment by gocejov** [comment]
@vintikzzz i just did

**Comment by gocejov** [comment]
@vintikzzz can you confirm that you get the message with the domain name?
