### ISSUE TITLE
Can webtor read the subtitle from the zip file URL

### ISSUE THREAD

**Issue by beshoo** [webtor-io/player-sdk-js#64]
Well, I create an API that uses https://subscene.com/ which is way better the included one "Opensubtitle"
Now "subscene" returns a ZIP file URL. 

How can I provide the STR ZIP file URL to webtor, my users will not know how to download it, extract it then upload it to webtor!
demo URL :

https://subscene.com/subtitles/arabic-text/zNFZxu6Xc74Alj4Y72CmH3QEMSVCKxpY7PzLfNjO1muraDES5rGN5o0FDvpV1LOD0kqh3vnhSULGt7cLnjr57hNtZKCCMHAys_n8_ANyPMpb94HRg5NUVp59aj5zFWLY0

BTW, a side question, do you support VAST, which we can monetize the player via displaying ads from google ads manager!
Am looking to subscribe with the bronze plan, to test the player without popup ads! so we may need to show our ads!

**Comment by beshoo** [comment]
or can you support https://subscene.com/ in your player?

**Comment by vintikzzz** [comment]
> Well, I create an API that uses https://subscene.com/ which is way better the included one "Opensubtitle"

You can inject your own subtitles via SDK, check [documentation](https://github.com/webtor-io/embed-sdk-js)
Subtitles must be in SRT or VTT format.

> BTW, a side question, do you support VAST, which we can monetize the player via displaying ads from google ads manager!

You can use [IMA SDK](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side) as overlay.
Don't forget to find demand with good CPM. Connecting to Google Ad Manager is just the beginning of the way.

> Am looking to subscribe with the bronze plan, to test the player without popup ads! so we may need to show our ads!

Well, you have to start with Silver to remove ads.

**Comment by beshoo** [comment]
Please check this 
>>Well, you have to start with Silver to remove ads.

![image](https://user-images.githubusercontent.com/4635115/157903235-fa156e20-35cf-4ecb-aa9d-b8f7f1de2089.png)

you already said no ads!

**Comment by vintikzzz** [comment]
"No ads" is for end user, who is visiting webtor.io directly. This doesn't apply to embeds. Sorry for misleading you.

**Comment by beshoo** [comment]
What do you mean?

The payment for the sdk, it is make no sense to pay whatever price and have
ads...

**Comment by vintikzzz** [comment]
Let me try to clarify all the things.

Originally all these membership levels (Bronze, Silver, Gold, etc) only removes ads and increases bandwidth for users that come directly to webtor.io site. So you can sign in at webtor.io with your Patreon account and get all benefits of your donation level.

At some point I introduced webtor embed SDK for site owners and they started to ask me about removing ads from webtor player at their own site. To fulfil this requirement, I just ask site owner to become my Patreon for any donation level starting from Silver.

Summering things up. To remove ads from your instance of embed SDK you have to get Patreon donation level starting from Silver and send me your site domain name in DM at Patreon.

**Comment by ghost** [comment]
I do not see DM option in Patreon. Is there any other way i can private message you?

**Comment by vintikzzz** [comment]
@kovacevica00 Sure! https://t.me/vintikzzzz
