### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by maxakash** [webtor-io/player-sdk-js#65]
Hi
I am building an android application that supports streaming without downloading content.
If I use your embed sdk js in a webview, then the user experience is very bad.
So, I was thinking, If I become your gold backer, is there any way I can get the streaming url.
I can then load it using the native video api for android.

Please let me know what you think.

**Comment by vintikzzz** [comment]
Hi! Next month I am going to implement "simple" API for end users. I think this should work for you.

**Comment by maxakash** [comment]
> Hi! Next month I am going to implement "simple" API for end users. I think this should work for you.

Hey @vintikzzz Sounds good.

**Comment by Inside4ndroid** [comment]
is there a way to remove the controls which are not needed for my scenario??


![controls](https://user-images.githubusercontent.com/65467186/160404198-7f969f1e-8833-42b1-a7ad-cec4f0ccec14.png)

for example i dont need the embed symbol so when using the below code is there something i should add to it??

` <div id="player" class="webtor" />
    <script>
        window.webtor = window.webtor || [];
        window.webtor.push({
            id: 'player',
            magnet: 'magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F',
            on: function(e) {
                if (e.name == window.webtor.TORRENT_FETCHED) {
                    console.log('Torrent fetched!', e.data);
                }
                if (e.name == window.webtor.TORRENT_ERROR) {
                    console.log('Torrent error!');
                }
            },
            poster: 'https://via.placeholder.com/150/0000FF/808080',
            subtitles: [
                {
                    srclang: 'en',
                    label: 'test',
                    src: 'https://raw.githubusercontent.com/andreyvit/subtitle-tools/master/sample.srt',
                    default: true,
                }
            ],
            lang: 'en',
            i18n: {
                en: {
                    common: {
                        "prepare to play": "Preparing Video Stream... Please Wait...",
                    },
                    stat: {
                        "seeding": "Seeding",
                        "waiting": "Client initialization",
                        "waiting for peers": "Waiting for peers",
                        "from": "from",
                    },
                },
            },
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@webtor/embed-sdk-js/dist/index.min.js" charset="utf-8" async></script>`
    
    Thank you :)

**Comment by maxakash** [comment]
Hey @vintikzzz , any update on this.
Thanks

**Comment by maxakash** [comment]
Hey @vintikzzz ,sorry to bother you again but any update on the API development?
Thanks

**Comment by maxakash** [comment]
> Hey @vintikzzz ,sorry to bother you again but any update on the API development? Thanks

Any updates @vintikzzz ?
THanks

**Comment by vintikzzz** [comment]
@maxakash Hi, I am really close to finish it, maybe in a week or so….

**Comment by vintikzzz** [comment]
[REST API](https://github.com/webtor-io/rest-api) is ready, and it is now part of [self-hosted installation](https://github.com/webtor-io/helm-charts). Later this week, I am going to make an integration with [RapidAPI](https://rapidapi.com/) and I think this will be the best option for you!

**Comment by maxakash** [comment]
> [REST API](https://github.com/webtor-io/rest-api) is ready, and it is now part of [self-hosted installation](https://github.com/webtor-io/helm-charts). Later this week, I am going to make an integration with [RapidAPI](https://rapidapi.com/) and I think this will be the best option for you!

Thank you very much @vintikzzz . Looking forward to it.

**Comment by vintikzzz** [comment]
I have finally published it at repidapi, here is a [link](https://rapidapi.com/paveltatarsky-Dx4aX7s_XBt/api/webtor/)

**Comment by maxakash** [comment]
> I have finally published it at repidapi, here is a [link](https://rapidapi.com/paveltatarsky-Dx4aX7s_XBt/api/webtor/)

Thanks @vintikzzz . I will try it ASAP.
