### ISSUE TITLE
Dos this player support HLS and MP4 from different origin 

### ISSUE THREAD

**Issue by beshoo** [webtor-io/player-sdk-js#67]
Dear support.
This is a wonderful piece of art.

One of the biggest problems we have with the media industry is the cross origin, we can not play m3u/mp4 from remote websites, since they did not provide a cross-origin, header, so the browser is blocking the streem.

It will be a great step if you can add this functionality to your player, as long as the pay seeking for the torrent streem and send it to the browser, I believe you can seek for the m3u streem or any mp4 and stream it via your player.

Please advice

**Comment by vintikzzz** [comment]
Hi, actually support of streaming of external mkv/mp4 is in a roadmap. I believe it could be implemented in the next few months.

**Comment by beshoo** [comment]
That's great, Am looking for this function long time. i hope you can provide it ASAP, next month maybe :)
