### ISSUE TITLE
Can I download only srt file from torrent?

### ISSUE THREAD

**Issue by ghost** [webtor-io/player-sdk-js#68]
https://webtor.io/#/show?file=All.The.Old.Knives.2022.720p.WEBRip.x264.AAC-%5BYTS.MX%5D.mp4&pwd=%2FAll%20The%20Old%20Knives%20%282022%29%20%5B720p%5D%20%5BWEBRip%5D%20%5BYTS.MX%5D&magnet=magnet%3A%3Fxt%3Durn%3Abtih%3A98e61c4f4e54027cbf76dca09a3e1f5fc40e3d12%26dn%3DAll%2BThe%2BOld%2BKnives%2B%282022%29%2B%255B720p%255D%2B%255BWEBRip%255D%2B%255BYTS.MX%255D

Is it possible to get direct link to first .srt file that is in main directory with SDK?

**Comment by vintikzzz** [comment]
@kovacevica00 Hi! Can you provide full use case? What functionality do you want?

**Comment by ghost** [comment]
I mainly stream movies from yts.mx with your SDK - advanced.html, all of the torrents have attached .srt file, which can be seen on https://webtor.io/ ( example url posted above )

This is direct link to .src file only, which i got from webtor.io:

https://abra--8ac92139.api.ftor.cc/98e61c4f4e54027cbf76dca09a3e1f5fc40e3d12/All%20The%20Old%20Knives%20(2022)%20%5B720p%5D%20%5BWEBRip%5D%20%5BYTS.MX%5D%2FAll.The.Old.Knives.2022.720p.WEBRip.x264.AAC-%5BYTS.MX%5D.srt~tc/All.The.Old.Knives.2022.720p.WEBRip.x264.AAC-%5BYTS.MX%5D.srt?user-id=7b485b15ad2daf85e718e0d6a652fe09&download=true&download-id=a049955bc95d55e918c244ee139a3156&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2VudCI6Ik1vemlsbGEvNS4wIChMaW51eDsgQW5kcm9pZCAxMjsgTTIxMDFLNkcpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xMDAuMC40ODk2LjU4IE1vYmlsZSBTYWZhcmkvNTM3LjM2IiwicmVtb3RlQWRkcmVzcyI6IjE4OC4xMjAuOTkuMTIzIiwiZG9tYWluIjoiZ2l0aHViLmNvbSIsImV4cCI6MTY1MDMwNjQ1NCwic2Vzc2lvbklEIjoiOTZUd1lWOHZtbWF2YWFKZVdOOHVXOFdTSTZIRVczQlIiLCJyYXRlIjoiMTBNIiwicm9sZSI6Im5vYm9keSJ9.Xbv7B9UYIz_vZCZD4KAG2uBdDgRw_jajYjUKobXnfKw&api-key=8acbcf1e-732c-4574-a3bf-27e6a85b86f1

I have an api that would translate the subtitle from direct link, so i need it to grab it somehow in the code, if it's possbible.

Lets say an api that would return torrent file content and direct link to it's download

**Comment by vintikzzz** [comment]
I am going to implement simple API that may cover all your needs. It was already discussed here #65.

**Comment by beshoo** [comment]
believe it or not, I am about to talk about the same thing.
@vintikzzz  Is the API will post the content to our Translation SDK URL and get the translated Content?

**Comment by vintikzzz** [comment]
You would have to download file from Webtor API, then push it to Translation API and finally get translated content.

Just to avoid possible future confusion, API will be available for:
1. [Patreon backers](https://www.patreon.com/pavel_tatarskiy?fan_landing=true) (starting from Silver tier).
2. [RapidApi](https://rapidapi.com/) subscribers.
3. For [self-hosted Webtor instances](https://github.com/webtor-io/helm-charts).
