### ISSUE TITLE
Auto subtitles

### ISSUE THREAD

**Issue by ghost** [webtor-io/player-sdk-js#69]
Since OpenSubtitles are most of the times wrong, 
Auto subtitles option for a specific language would get this project to a new level. 
What do you think?

**Comment by vintikzzz** [comment]
You can set specific user language by setting `userLang` option.

**Comment by ghost** [comment]
I meant subtitle generation by speech recognition or something similar if that is possible

**Comment by vintikzzz** [comment]
I've found several services that can provide such recognition ([like this one](https://cloud.google.com/speech-to-text)), but they are quite expensive (5+ USD per movie). If you can provide another option, it will be great!
