### ISSUE TITLE
Player is freezing sometimes 

### ISSUE THREAD

**Issue by beshoo** [webtor-io/player-sdk-js#70]
Sometimes when press on the play button, player start the loading, then all interfaces are disappear but the poster photo remain.

And sometimes while watching, all controls are disappears. And you needed to reload the page.

Am not sure if you can reproduce this problem.

https://aflam.vip/movie/927070/polar-bear-2022-720p-webrip-800mb-x264-galaxyrg[tgx]/watch_torrent?s=torlock&i=da6da134&orgi=Polar%20Bear

**Comment by vintikzzz** [comment]
I have updated a few libraries and dropped some logic. Maybe this should help.

**Comment by beshoo** [comment]
Unfortunately it dos not, test the link i provided, it's happening when stard seed begins
