### ISSUE TITLE
How to change options in player

### ISSUE THREAD

**Issue by flgi1** [webtor-io/player-sdk-js#73]
Hi,

How can i change options in player, a want to hide "embed" icon and "sttings" and "download" is that posible ?

**Comment by vintikzzz** [comment]
#43

**Comment by flgi1** [comment]
Thx U man, its work. I need a one more thinik. How can i get autosubttile for example serbian language

**Comment by vintikzzz** [comment]
just use `userLang` option

**Comment by flgi1** [comment]
I am not good on this man sry, is it possbile to send me an example code ?

**Comment by vintikzzz** [comment]
Just check [this example](https://github.com/webtor-io/embed-sdk-js#advanced-usage) and add there `userLang: 'sr'`
