### ISSUE TITLE
Cheap porno ads playing

### ISSUE THREAD

**Issue by odmivolsi** [webtor-io/player-sdk-js#8]
I'm trying to create a webtorrent based video player and I've excluded all adult content from playing on the site, apart from your ads. You've built a really good player but what's the point when you are ending up showing ads for pornos?

**Comment by hlpokumr** [comment]
Yes i had same issue. How to fix?

**Comment by wlasser** [comment]
> Yes i had same issue. How to fix?

use you own webtor instance, or support author on patreon (something he told about it or other, didn't remember).

But realy, maybe you review ads politics - as i see - there is many from black listed markets platforms - "enlarge you penis", "watch this pussys" and other.
Man, don't kill you child with cheap money.

**Comment by odmivolsi** [comment]
> > Yes i had same issue. How to fix?
> 
> use you own webtor instance, or support author on patreon (something he told about it or other, didn't remember).
> 
> But realy, maybe you review ads politics - as i see - there is many from black listed markets platforms - "enlarge you penis", "watch this pussys" and other.
> Man, don't kill you child with cheap money.

Exactly. What do you mean by using my own webtor instance?

**Comment by hlpokumr** [comment]
> > Yes i had same issue. How to fix?
> 
> use you own webtor instance, or support author on patreon (something he told about it or other, didn't remember).

Hey thanks for your help 😊. I don't have enough money to support his patreon right now, I might do it in the future though.

For now, can you pls guide me how to setup my own webtor instance??
Thanks:)

**Comment by vintikzzz** [comment]
Hi! I have removed all adult ads from all ad networks few days ago. I don't really want to show them at mainstream sites at all. Maybe some networks ignores my preferences. I will check it shortly. Thanks for notification.

> For now, can you pls guide me how to setup my own webtor instance??

@hlpokumr https://github.com/webtor-io/helm-charts

**Comment by odmivolsi** [comment]
> > For now, can you pls guide me how to setup my own webtor instance??
> 
> @hlpokumr https://github.com/webtor-io/helm-charts

If I do this can I remove the ads? Or even add my own ads to keep up with hosting expenses?

**Comment by hlpokumr** [comment]
> Hi! I have removed all adult ads from all ad networks few days ago. I don't really want to show them at mainstream sites at all. Maybe some networks ignores my preferences. I will check it shortly. Thanks for notification.
> 
> > For now, can you pls guide me how to setup my own webtor instance??
> 
> @hlpokumr https://github.com/webtor-io/helm-charts

@vintikzzz Good job brother! Atleast you have tried to remove them, however i saw them running in the morning today too but it maybe due to latency on the part of the ad provider.

@odmivolsi yes brother the hosting plans are way too much for me to handle and in this pandemic world I don't know if I can sustain it and myself too.

**Comment by vintikzzz** [comment]
@odmivolsi it will bring you platform that just streams content from torrent and you should build player on your own.
https://github.com/webtor-io/platform-sdk-js - is a js sdk that makes it possbile to work with it and build your own solution.

**Comment by odmivolsi** [comment]
@vintikzzz alright thanks man! I hope I can soon contribute on your patreon 😄

**Comment by vintikzzz** [comment]
I have found "porn leakage"! Closing now!
@odmivolsi thanks!
