### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME on Vuejs

### ISSUE THREAD

**Issue by ZulluBalti** [webtor-io/player-sdk-js#82]
Hi,

I'm using Vuejs to create this app which allows watching torrent files online. But I'm getting this error that says "ERR_UNKNOWN_URL_SCHEME"

I've checked the magnetic link with a simple HTML file (and of webtor js file too) and it works but on my vue app it's not working. I'm importing the script file there too

**Comment by vintikzzz** [comment]
Hi! Please provide example page.

**Comment by ZulluBalti** [comment]
thanks for the reply but I solved the issue. 

The issue was I was adding the js file using the script tag in the index.html file which was not working. 
Adding the script by using the createElement("script") function in the mounted method solves the issue.
