### ISSUE TITLE
плеер настройка

### ISSUE THREAD

**Issue by patrikfun** [webtor-io/player-sdk-js#89]
здрасти

если поставить твой плеер на свой сайт, можно как то сделать чтобы убрать реклму, например када капируешь плеер код с твоего сайта и вставляешь к себе на сайт, то там постояно реклама прыгает, как можно убрать рекламу

и если можно еще спросить, как сделать чтобы например када пользователь зашел на сайт и кликнул на воспроизвидение видео, чтобы русские субтитры автоматически по умолчанию начали работать, это чтобы пользователи не ковырялись и сами субтитры не ставили, потому что я хочу использовать свои файлы субтитров, вот как сделать чтобы уже автомотичсеки субтитры начали работать?

**Comment by vintikzzz** [comment]
> если поставить твой плеер на свой сайт, можно как то сделать чтобы убрать рекламу, например когда копируешь плеер код с твоего сайта и вставляешь к себе на сайт, то там постоянно реклама прыгает, как можно убрать рекламу

Реклама убирается через донат на патреоне (от 5USD в месяц). После доната нужно скинуть мне в личке имя домена и я отключу для этого него рекламу. Пока работает так.

> и если можно еще спросить, как сделать чтобы например когда пользователь зашел на сайт и кликнул на воспроизвидение видео, чтобы русские субтитры автоматически по умолчанию начали работать, это чтобы пользователи не ковырялись и сами субтитры не ставили, потому что я хочу использовать свои файлы субтитров, вот как сделать чтобы уже автомотичсеки субтитры начали работать?

Если подгружены субтитры соответствующие языку браузера пользователя, то субтитры подключаются автоматически. Язык можно переопределять через параметры `userLang`. При подгрузке своих субтитров обязательно надо указывать корректно `srclang` (в нашем случае `ru`) иначе схема работать не будет.
