### ISSUE TITLE
Subtitles not showing in full screen on Android Smartphones.

### ISSUE THREAD

**Issue by redehaka** [webtor-io/player-sdk-js#9]
Everytime I go full screen the subtitles will not show up on my phone but Everytime I don’t go full screen the subtitles show up!

**Comment by odmivolsi** [comment]
Can you pls provide a link? Subtitles don't work for me at all on mobile, let alone full-screen

**Comment by odmivolsi** [comment]
Same issue here

**Comment by redehaka** [comment]
Contributor please fix subtitles in full screen on Android!

**Comment by wlasser** [comment]
I know how do fix this! Use hardsubs! =)
Can you check this on random browsers? For example Firefox and UCBrowser.
I realy don't know how this help to @vintikzzz , but for better practice of reporting - try to give a better/stronger/harder research and report.

**Comment by odmivolsi** [comment]
@wlasser how do i hardsub a torrent?

**Comment by vintikzzz** [comment]
@redehaka do you use embedded subs or select something from OpenSubtitles? or this error occurs with every sub?

**Comment by redehaka** [comment]
I use embedded subtitles, external subtitles too, when player is in fullscreen not show subtitles.

**Comment by redehaka** [comment]
![screenshot_20201022_040252](https://user-images.githubusercontent.com/59845014/96806873-dbd97200-141d-11eb-89a3-2c81e755b32b.jpg)
![screenshot_20201022_041346](https://user-images.githubusercontent.com/59845014/96806889-e562da00-141d-11eb-88ab-d86da0d37621.jpg)
This is player not in fullscreen with subtitles.

![screenshot_20201022_041501](https://user-images.githubusercontent.com/59845014/96806957-13481e80-141e-11eb-8e68-9f685e385e66.jpg)
This is player in fullscreen no subtitles showing.

**Comment by vintikzzz** [comment]
Yes, there is some issues with it, android native player doesn't see subtitles that were added dynamically to the player. I will try to find a walkaround for this

**Comment by vintikzzz** [comment]
Hi! It seems I fixed this. Can you check?

**Comment by redehaka** [comment]
Hi, yes now I have subtitles in fullscreen, good job.

**Comment by vintikzzz** [comment]
Thank's! Sorry that it takes too long to fix this!
